### ISSUE TITLE
CI workflows are very slow

### ISSUE THREAD

**Issue by droserasprout** [dipdup-net/dipdup#466]
- [x] Poetry resolution speed is still terrible, 1.2.0 doesn't add much
- [ ] GitHub has no native arm64 builds. QEMU BuildX integration works fine but, again, veeeery slow
- [x] Enforce locked deps for dipdup?
- [x] Do not run the whole matrix on each build
- [x] We're out of cache
- [ ] Drop -pytezos?

**Comment by droserasprout** [comment]
Pretty much fixed. Related: #486
